version: '2'
services:
  bot:
    build:
      context: .
      dockerfile: local/Dockerfile
    env_file: local/local.env
    volumes:
      - "./src/bot:/usr/src/app/bot"

  dynamo:
    image: amazon/dynamodb-local
    hostname: dynamo
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1
  
  init-dynamo:
    image: garland/aws-cli-docker
    command: "aws dynamodb create-table --table-name messages --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamo:8000"
    links:
      - dynamo
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1